
export const mockData = {
  items: [
    {'rating': 8.8, 'genres': ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'], 'rated': 'PG', 'language': ['English'], 'title': 'Star Wars'},
    {'rating': 8.1, 'genres': ['Animation', 'Adventure', 'Comedy', 'Family'], 'rated': 'G', 'language': ['English'], 'title': 'Finding Nemo'},
    {'rating': 8.7, 'genres': ['Drama', 'Romance'], 'rated': 'PG-13', 'language': ['English'], 'title': 'Forrest Gump'},
    {'rating': 8.5, 'genres': ['Drama'], 'language': ['English'], 'title': 'American Beauty'},
    {'rating': 8.0, 'genres': ['Action', 'Adventure', 'Fantasy'], 'rated': 'PG-13', 'language': ['English'], 'title': 'Pirates of the Caribbean: The Curse of the Black Pearl'},
    {'rating': 8.2, 'genres': ['Action', 'Crime'], 'language': ['English', 'Japanese', 'French'], 'title': 'Kill Bill: Vol. 1'},
    {'rating': 8.4, 'genres': ['Drama', 'Romance', 'Sci-Fi'], 'rated': 'R', 'language': ['English'], 'title': 'Eternal Sunshine of the Spotless Mind'},
    {'rating': 8.1, 'genres': ['Mystery', 'Sci-Fi', 'Thriller'], 'rated': 'R', 'language': ['English', 'French'], 'title': 'Twelve Monkeys'},
    {'rating': 8.6, 'genres': ['Mystery', 'Thriller'], 'rated': 'R', 'language': ['English'], 'title': 'Memento'},
    {'rating': 8.6, 'genres': ['Action', 'Adventure'], 'rated': 'PG', 'language': ['English', 'German', 'Hebrew', 'Spanish', 'Arabic', 'Nepali'], 'title': 'Raiders of the Lost Ark'},
    {'rating': 8.5, 'genres': ['Action', 'Adventure', 'Drama'], 'rated': 'R', 'language': ['English'], 'title': 'Gladiator'},
    {'rating': 8.5, 'genres': ['Adventure', 'Comedy', 'Sci-Fi'], 'language': ['English'], 'title': 'Back to the Future'},
    {'rating': 8.3, 'genres': ['Crime', 'Thriller'], 'rated': 'R', 'language': ['English', 'Russian'], 'title': 'Snatch.'},
    {'rating': 6.8, 'genres': ['Comedy', 'Romance'], 'rated': 'R', 'language': ['English', 'Italian', 'Japanese'], 'title': 'Pretty Woman'},
    {'rating': 8.8, 'genres': ['Action', 'Adventure', 'Fantasy'], 'rated': 'PG-13', 'language': ['English', 'Sindarin'], 'title': 'The Lord of the Rings: The Fellowship of the Ring'},
    {'rating': 8.7, 'genres': ['Action', 'Adventure', 'Fantasy'], 'rated': 'PG-13', 'language': ['English', 'Sindarin', 'Old English'], 'title': 'The Lord of the Rings: The Two Towers'},
    {'rating': 8.9, 'genres': ['Action', 'Adventure', 'Fantasy'], 'rated': 'PG-13', 'language': ['English', 'Quenya', 'Old English', 'Sindarin'], 'title': 'The Lord of the Rings: The Return of the King'},
    {'rating': 7.8, 'genres': ['Comedy', 'Adventure', 'Crime', 'Music'], 'rated': '12', 'language': ['English'], 'title': 'O Brother, Where Art Thou?'},
    {'rating': 8.1, 'genres': ['Drama', 'Mystery', 'Sci-Fi'], 'rated': 'R', 'language': ['English'], 'title': 'Donnie Darko'},
    {'rating': 6.9, 'genres': ['Action', 'Adventure', 'Drama', 'Fantasy', 'Romance'], 'language': ['Mandarin'], 'title': 'Crouching Tiger, Hidden Dragon'},
    {'rating': 7.8, 'genres': ['Drama'], 'rated': 'R', 'language': ['English', 'Japanese', 'German', 'French'], 'title': 'Lost in Translation'},
    {'rating': 9.0, 'genres': ['Action', 'Crime', 'Drama', 'Thriller'], 'rated': 'PG-13', 'language': ['English', 'Mandarin'], 'title': 'The Dark Knight'},
    {'rating': 7.7, 'genres': ['Action', 'Mystery', 'Sci-Fi', 'Thriller'], 'rated': 'PG-13', 'language': ['English', 'Swedish'], 'title': 'Minority Report'},
    {'rating': 8.2, 'genres': ['Crime', 'Thriller'], 'language': ['English'], 'title': 'Sin City'},
    {'rating': 5.7, 'genres': ['Adventure', 'Biography', 'Drama', 'Romance'], 'rated': 'PG', 'language': ['English'], 'title': 'Amelia'},
    {'rating': 8.4, 'genres': ['Action', 'Biography', 'Drama', 'History', 'War'], 'rated': 'R', 'language': ['English', 'French', 'Latin', 'Scottish Gaelic'], 'title': 'Braveheart'},
    {'rating': 9.2, 'genres': ['Crime', 'Drama'], 'rated': 'R', 'language': ['English', 'Italian', 'Latin'], 'title': 'The Godfather'},
    {'rating': 7.5, 'genres': ['Comedy', 'Drama', 'Music', 'Romance'], 'rated': 'R', 'language': ['English', 'Danish'], 'title': 'High Fidelity'},
    {'rating': 8.3, 'genres': ['Action', 'Adventure', 'Crime', 'Drama'], 'rated': 'PG-13', 'language': ['English', 'Urdu', 'Mandarin'], 'title': 'Batman Begins'},
    {'rating': 8.3, 'genres': ['Action', 'Adventure', 'Crime', 'Drama'], 'rated': 'PG-13', 'language': ['English', 'Urdu', 'Mandarin'], 'title': 'Batman Begins'},
    {'rating': 8.7, 'genres': ['Crime', 'Drama', 'Thriller'], 'language': ['English'], 'title': 'Le silence des agneaux The Silence of the Lambs\''},
    {'rating': 8.2, 'genres': ['Crime', 'Drama', 'Thriller'], 'rated': 'R', 'language': ['English'], 'title': 'Fargo'},
    {'rating': 9.3, 'genres': ['Crime', 'Drama'], 'language': ['English'], 'title': 'shanku no sora ni The Shawshank Redemption\''},
    {'rating': 8.6, 'genres': ['Action', 'Sci-Fi', 'Thriller'], 'rated': 'R', 'language': ['English', 'Spanish'], 'title': 'Terminator 2: Judgment Day'},
    {'rating': 8.0, 'genres': ['Adventure', 'Sci-Fi'], 'rated': 'PG-13', 'language': ['English', 'Spanish'], 'title': 'Jurassic Park'},
    {'rating': 8.0, 'genres': ['Action', 'Crime', 'Thriller'], 'language': ['English', 'Cantonese', 'Mandarin', 'Spanish'], 'title': 'Kill Bill Vol. 2: The Love Story Kill Bill: Vol. 2'},
    {'rating': 5.4, 'genres': ['Action', 'Adventure', 'Fantasy'], 'rated': 'PG-13', 'language': ['English'], 'title': 'Batman Forever'},
    {'rating': 8.9, 'genres': ['Biography', 'Drama', 'History', 'War'], 'rated': 'R', 'language': ['English', 'Hebrew', 'German', 'Polish'], 'title': 'Schindlers List'},
    {'rating': 8.1, 'genres': ['Biography', 'Drama'], 'rated': 'PG-13', 'language': ['English'], 'title': 'A Beautiful Mind'},
    {'rating': 7.2, 'genres': ['Biography', 'Drama'], 'rated': 'R', 'language': ['English'], 'title': 'Erin Brockovich'},
    {'rating': 8.9, 'genres': ['Drama'], 'rated': 'R', 'language': ['English'], 'title': 'Fight Club'},
    {'rating': 5.5, 'genres': ['Adventure', 'Crime'], 'language': ['Turkish'], 'title': 'rmcek adam'},
    {'rating': 7.5, 'genres': ['Adventure', 'Drama', 'History'], 'rated': 'PG', 'language': ['English'], 'title': 'Apollo 13'},
    {'rating': 8.0, 'genres': ['Adventure', 'Drama', 'Western'], 'rated': 'PG-13', 'language': ['English', 'Sioux', 'Pawnee'], 'title': 'Dances with Wolves'},
    {'rating': 8.0, 'genres': ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'], 'rated': 'G', 'language': ['English'], 'title': 'Monsters, Inc.'},
    {'rating': 7.6, 'genres': ['Drama', 'Romance'], 'rated': 'PG-13', 'language': ['English', 'French', 'German', 'Swedish', 'Italian', 'Russian'], 'title': 'Titanic'},
    {'rating': 7.9, 'genres': ['Adventure', 'Family', 'Fantasy', 'Sci-Fi'], 'language': ['English'], 'title': 'E.T. the Extra-Terrestrial'},
    {'rating': 6.8, 'genres': ['Action', 'Adventure', 'Sci-Fi', 'Thriller'], 'language': ['English'], 'title': 'Independence Day'},
    {'rating': 8.7, 'genres': ['Action', 'Adventure', 'Sci-Fi'], 'rated': 'R', 'language': ['English'], 'title': 'The Matrix'},
    {'rating': 7.1, 'genres': ['Action', 'Sci-Fi'], 'rated': 'R', 'language': ['English', 'French'], 'title': 'The Matrix Reloaded'},
    {'rating': 7.2, 'genres': ['Comedy', 'Sci-Fi'], 'rated': 'PG-13', 'language': ['English', 'Spanish'], 'title': 'Men in Black'},
    {'rating': 8.7, 'genres': ['Crime', 'Mystery', 'Thriller'], 'rated': 'R', 'language': ['English', 'Hungarian', 'Spanish', 'French'], 'title': 'The Usual Suspects'},
    {'rating': 7.9, 'genres': ['Biography', 'Comedy', 'Crime', 'Drama'], 'rated': 'PG-13', 'language': ['English', 'French'], 'title': 'Catch Me If You Can'},
    {'rating': 8.4, 'genres': ['Drama'], 'rated': 'R', 'language': ['English'], 'title': 'Requiem for a Dream'},
    {'rating': 6.1, 'genres': ['Action', 'Adventure', 'Drama', 'Thriller'], 'rated': 'PG-13', 'language': ['English'], 'title': 'Twister'},
    {'rating': 7.3, 'genres': ['Adventure', 'Family', 'Fantasy'], 'rated': 'PG', 'language': ['English'], 'title': 'Harry Potter and the Sorcerers Stone'},
    {'rating': 7.2, 'genres': ['Adventure', 'Family', 'Fantasy', 'Mystery'], 'rated': 'PG', 'language': ['English'], 'title': 'Harry Potter and the Chamber of Secrets'},
    {'rating': 9.0, 'genres': ['Crime', 'Drama', 'Thriller'], 'rated': 'R', 'language': ['English', 'Spanish', 'French'], 'title': 'Pulp Fiction'},
    {'rating': 8.2, 'genres': ['Drama', 'Mystery', 'Thriller'], 'language': ['English', 'Latin', 'Spanish'], 'title': 'The Sixth Sense'},
    {'rating': 8.2, 'genres': ['Action', 'Crime', 'Fantasy', 'Mystery', 'Sci-Fi', 'Thriller'], 'rated': 'R', 'language': ['English'], 'title': 'V for Vendetta'},
    {'rating': 7.9, 'genres': ['Drama', 'Music'], 'rated': 'R', 'language': ['English'], 'title': 'Almost Famous'},
    {'rating': 6.7, 'genres': ['Comedy', 'Drama'], 'rated': 'PG-13', 'language': ['English'], 'title': 'Mrs. Doubtfire'},
    {'rating': 7.5, 'genres': ['Drama'], 'rated': 'PG-13', 'language': ['English', 'Spanish'], 'title': 'Seven Pounds'},
    {'rating': 7.9, 'genres': ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'], 'rated': 'PG', 'language': ['English'], 'title': 'Shrek'},
    {'rating': 7.3, 'genres': ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'], 'language': ['English'], 'title': 'Shrek 2'},
    {'rating': 7.9, 'genres': ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy', 'Musical', 'Romance'], 'rated': 'G', 'language': ['English'], 'title': 'Aladdin'},
    {'rating': 6.8, 'genres': ['Comedy', 'Crime', 'Fantasy', 'Romance'], 'rated': 'PG-13', 'language': ['English', 'Swedish'], 'title': 'The Mask'},
    {'rating': 8.6, 'genres': ['Action', 'Drama', 'War'], 'rated': '16', 'language': ['English', 'French', 'German', 'Czech'], 'title': 'Der Soldat James Ryan Saving Private Ryan'},
    {'rating': 8.3, 'genres': ['Animation', 'Adventure', 'Comedy', 'Family', 'Fantasy'], 'language': ['English'], 'title': 'Toy Story'},
    {'rating': 7.4, 'genres': ['Action', 'Thriller'], 'rated': 'PG-13', 'language': ['English', 'Russian', 'French', 'Arabic', 'Swedish'], 'title': 'Mission: Impossible - Ghost Protocol'},
    {'rating': 5.9, 'genres': ['Action', 'Adventure', 'Thriller'], 'rated': 'PG-13', 'language': ['English'], 'title': 'Mission: Impossible II'},
    {'rating': 8.5, 'genres': ['Crime', 'Drama', 'Thriller'], 'language': ['English', 'Cantonese'], 'title': 'The Departed'},
    {'rating': 7.5, 'genres': ['Action', 'Crime', 'Thriller'], 'rated': 'R', 'language': ['English', 'German', 'Romanian'], 'title': 'Die Hard: With a Vengeance'},
    {'rating': 7.0, 'genres': ['Comedy', 'Romance'], 'rated': 'PG-13', 'language': ['English', 'Thai', 'Spanish', 'Hebrew', 'French'], 'title': 'Meet the Parents'},
    {'rating': 7.2, 'genres': ['Action', 'Thriller'], 'rated': 'R', 'language': ['English'], 'title': 'Speed'},
    {'rating': 8.8, 'genres': ['Action', 'Adventure', 'Sci-Fi'], 'rated': 'PG', 'language': ['English'], 'title': 'Star Wars: Episode V - The Empire Strikes Back'},
    {'rating': 8.4, 'genres': ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'], 'rated': 'PG', 'language': ['English'], 'title': 'Star Wars: Episode VI - Return of the Jedi'},
    {'rating': 6.7, 'genres': ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'], 'language': ['English'], 'title': 'Star Wars: Episode II - Ataque dos Clones Star Wars: Episode II - Attack of the Clones\''},
    {'rating': 7.7, 'genres': ['Crime', 'Drama', 'Thriller'], 'rated': 'R', 'language': ['English', 'Spanish'], 'title': 'Traffic'},
    {'rating': 7.0, 'genres': ['Action', 'Drama', 'War'], 'rated': 'R', 'language': ['English'], 'title': 'The Patriot'},
    {'rating': 6.9, 'genres': ['Action', 'Adventure', 'Sci-Fi'], 'language': ['English', 'Norwegian', 'Swedish'], 'title': 'Stargate'},
    {'rating': 7.9, 'genres': ['Action', 'Mystery', 'Thriller'], 'language': ['English', 'French', 'German', 'Dutch', 'Italian'], 'title': 'Identidade Desconhecida The Bourne Identity\''},
    {'rating': 7.7, 'genres': ['Action', 'Crime', 'Thriller'], 'rated': 'T', 'language': ['English', 'Russian', 'German', 'Italian'], 'title': 'The Bourne Supremacy'},
    {'rating': 6.8, 'genres': ['Comedy'], 'rated': 'PG-13', 'language': ['English'], 'title': 'Ace Ventura: Pet Detective'},
    {'rating': 5.5, 'genres': ['Action', 'Adventure', 'Comedy', 'Crime', 'Thriller'], 'rated': 'PG-13', 'language': ['English', 'German', 'Finnish', 'Japanese', 'Cantonese'], 'title': 'Charlies Angels'},
    {'rating': 7.8, 'genres': ['Action', 'Adventure', 'Crime', 'Mystery', 'Thriller'], 'rated': 'PG-13', 'language': ['English', 'Polish', 'Spanish'], 'title': 'The Fugitive'},
    {'rating': 7.1, 'genres': ['Animation', 'Family', 'Comedy'], 'rated': 'G', 'language': ['English'], 'title': 'Chicken Run'},
    {'rating': 7.6, 'genres': ['Adventure', 'Drama'], 'rated': 'PG-13', 'language': ['English', 'Russian'], 'title': 'Cast Away'},
    {'rating': 7.2, 'genres': ['Comedy'], 'rated': 'PG-13', 'language': ['English', 'Swedish', 'German'], 'title': 'Dumb &amp; Dumber'},
    {'rating': 8.4, 'genres': ['Animation', 'Adventure', 'Drama', 'Family', 'Musical'], 'language': ['English', 'Swahili', 'Xhosa', 'Zulu'], 'title': 'The Lion King'},
    {'rating': 6.8, 'genres': ['Action', 'Drama', 'Thriller'], 'rated': 'PG-13', 'language': ['English'], 'title': 'Clear and Present Danger'},
    {'rating': 7.2, 'genres': ['Drama', 'Mystery', 'Sci-Fi', 'Thriller'], 'rated': 'PG-13', 'language': ['English'], 'title': 'Unbreakable'},
    {'rating': 7.3, 'genres': ['Action', 'Adventure', 'Thriller'], 'rated': 'R', 'language': ['English'], 'title': 'The Rock'},
    {'rating': 8.0, 'genres': ['Animation', 'Action', 'Adventure', 'Family'], 'rated': 'PG', 'language': ['English', 'French'], 'title': 'The Incredibles'},
    {'rating': 8.0, 'genres': ['Animation', 'Family', 'Fantasy', 'Musical', 'Romance'], 'rated': 'G', 'language': ['English', 'French'], 'title': 'Beauty and the Beast'},
    {'rating': 5.4, 'genres': ['Comedy'], 'rated': 'R', 'language': ['English'], 'title': 'Women vs. Men'},
    {'rating': 7.2, 'genres': ['Action', 'Thriller'], 'rated': 'R', 'language': ['English', 'French', 'Arabic', 'German'], 'title': 'True Lies'}
  ]
};
